//! The host bindings of `wit/v1/serialist-codec.wit`, generated by wasmtime.

wasmtime::component::bindgen!({
    path: "wit/v1",
    world: "serialist:codec/plugin",
    additional_derives: [PartialEq],
});
