//! The theme keys the app reads, from the plan's theme-key table. A Zed theme defines
//! many more; the rest are kept and ignored.

/// The 16 terminal colors in the standard order: black, red, green, yellow, blue,
/// magenta, cyan, white, then the bright form of each.
pub const TERMINAL_ANSI_KEYS: [&str; 16] = [
    "terminal.ansi.black",
    "terminal.ansi.red",
    "terminal.ansi.green",
    "terminal.ansi.yellow",
    "terminal.ansi.blue",
    "terminal.ansi.magenta",
    "terminal.ansi.cyan",
    "terminal.ansi.white",
    "terminal.ansi.bright_black",
    "terminal.ansi.bright_red",
    "terminal.ansi.bright_green",
    "terminal.ansi.bright_yellow",
    "terminal.ansi.bright_blue",
    "terminal.ansi.bright_magenta",
    "terminal.ansi.bright_cyan",
    "terminal.ansi.bright_white",
];

/// Every flat style key the app reads. The bundled themes define all of them, so
/// `color_or` is only needed for user themes that leave some out.
pub const USED_STYLE_KEYS: &[&str] = &[
    // Scrollback text and ANSI rendering.
    "terminal.background",
    "terminal.foreground",
    "terminal.bright_foreground",
    "terminal.dim_foreground",
    "terminal.ansi.black",
    "terminal.ansi.red",
    "terminal.ansi.green",
    "terminal.ansi.yellow",
    "terminal.ansi.blue",
    "terminal.ansi.magenta",
    "terminal.ansi.cyan",
    "terminal.ansi.white",
    "terminal.ansi.bright_black",
    "terminal.ansi.bright_red",
    "terminal.ansi.bright_green",
    "terminal.ansi.bright_yellow",
    "terminal.ansi.bright_blue",
    "terminal.ansi.bright_magenta",
    "terminal.ansi.bright_cyan",
    "terminal.ansi.bright_white",
    // Window chrome, docks and tabs.
    "background",
    "surface.background",
    "elevated_surface.background",
    "panel.background",
    "panel.focused_border",
    "title_bar.background",
    "title_bar.inactive_background",
    "status_bar.background",
    "tab_bar.background",
    "tab.inactive_background",
    "tab.active_background",
    "toolbar.background",
    // Buttons, lists, inputs and focus rings.
    "element.background",
    "element.hover",
    "element.active",
    "element.selected",
    "element.disabled",
    "ghost_element.background",
    "ghost_element.hover",
    "ghost_element.active",
    "ghost_element.selected",
    "ghost_element.disabled",
    "border",
    "border.variant",
    "border.focused",
    "border.selected",
    "border.transparent",
    "border.disabled",
    "text",
    "text.muted",
    "text.placeholder",
    "text.disabled",
    "text.accent",
    "icon",
    "icon.muted",
    "icon.placeholder",
    "icon.disabled",
    "icon.accent",
    "scrollbar.thumb.background",
    "scrollbar.thumb.hover_background",
    "scrollbar.thumb.border",
    "scrollbar.track.background",
    "scrollbar.track.border",
    // Scrollback search.
    "search.match_background",
    "search.active_match_background",
    // Connection state, TX/RX/decoded accents and script results.
    "success",
    "success.background",
    "success.border",
    "warning",
    "warning.background",
    "warning.border",
    "error",
    "error.background",
    "error.border",
    "info",
    "info.background",
    "info.border",
    "hint",
    "hint.background",
    "hint.border",
];

/// The `syntax` captures the app reads, for decoded frame fields and the script console.
pub const USED_SYNTAX_KEYS: &[&str] = &["number", "string", "keyword", "comment"];
