//! A capture recorded from the simulated RACE device, replayed through the real replay
//! transport and session into the Rust and Lua RACE codecs, which must agree with
//! decoding the file directly. No hardware.
//!
//! The capture is `tests/fixtures/race-session.bin` plus its timing sidecar
//! `race-session.bin.timing`, both written by [`serialist_sim::record_device`] on a
//! manual clock, so they are a pure function of the device and the settings below and
//! can be regenerated byte for byte. After an intended change to the device or to the
//! recording, rewrite them with
//!
//! ```text
//! SERIALIST_BLESS_FIXTURES=1 cargo test -p serialist-plugins --test replay_conformance
//! ```
//!
//! (the other tests in this file read the fixture while that run rewrites it, so run
//! the file again afterwards without the variable), then pin the new frames with
//! `INSTA_UPDATE=always cargo test -p serialist-plugins --test replay_conformance` (or
//! `cargo insta review`) and read the snapshot diff in
//! `tests/fixtures/snapshots/race_session_frames.snap`.

mod common;

use std::path::PathBuf;
use std::sync::Arc;
use std::time::{Duration, Instant};

use serialist_core::{
    CodecFactory, CodecSink, Frame, FrameStore, Ingest, REPLAY_SCHEME, ReplayAddress, ReplaySpeed,
    ReplayTransportFactory, RoutingTransportFactory, SerialConfig, SerialportFactory, Session,
    SessionConfig, Transport, TransportError, TransportFactory,
};
use serialist_plugins::race::AirohaRace;
use serialist_plugins::{LuaLimits, bundled_race_lua};
use serialist_sim::{Capture, LinkConfig, ManualClock, RaceDevice, record_device};

use common::{decode_chunks, fixtures, render, timeless};

/// How much simulated time the fixture covers, and how often the clock steps.
const DURATION: Duration = Duration::from_secs(2);
const STEP: Duration = Duration::from_millis(5);
const LOG_INTERVAL: Duration = Duration::from_millis(20);
/// The fixture stays small enough to commit without a second thought.
const MAX_FIXTURE_BYTES: usize = 64 * 1024;

/// Recorded in the fixture's own words: a RACE device logging every 20 ms on a paced
/// 115200 baud link, watched for 2 s in 5 ms steps.
fn record() -> Capture {
    record_device(
        Box::new(RaceDevice::new().with_log_interval(Some(LOG_INTERVAL))),
        LinkConfig::default(),
        DURATION,
        STEP,
    )
}

fn raw_path() -> PathBuf {
    fixtures().join("race-session.bin")
}

fn fixture() -> Capture {
    Capture::read_from(&raw_path()).expect("the capture fixture is checked in, with its sidecar")
}

#[test]
fn recording_the_device_is_deterministic() {
    let first = record();
    let second = record();
    assert!(first.raw == second.raw, "the raw bytes differ between runs");
    assert!(
        first.timing == second.timing,
        "the timing sidecar differs between runs:\n{}\n--- vs ---\n{}",
        String::from_utf8_lossy(&first.timing),
        String::from_utf8_lossy(&second.timing)
    );
}

#[test]
fn the_fixture_is_the_recorded_device() {
    let recorded = record();
    if std::env::var_os("SERIALIST_BLESS_FIXTURES").is_some() {
        recorded.write_to(&raw_path()).expect("write the fixture");
    }
    let committed = fixture();
    assert!(
        committed.raw == recorded.raw && committed.timing == recorded.timing,
        "the capture fixture no longer matches the device; see this file's docs to rewrite it"
    );
    assert!(committed.raw.len() < MAX_FIXTURE_BYTES);
    assert!(committed.timing.len() < MAX_FIXTURE_BYTES);
}

/// What `replay:` ids route to in the app, on `replay`'s clock. The serial default is
/// never reached.
fn router(replay: ReplayTransportFactory) -> RoutingTransportFactory {
    RoutingTransportFactory::new(Arc::new(SerialportFactory::new()))
        .with_scheme(REPLAY_SCHEME, Arc::new(replay))
}

/// Replay the fixture at `speed=max` through the router and a real `Session` into a
/// codec made by `factory`, wait for the session to end, and return what was decoded
/// along with the chunk count the ingest thread saw.
fn replay_decoded(factory: Arc<dyn CodecFactory>) -> (Vec<Frame>, u64) {
    let router = router(ReplayTransportFactory::new());
    let id = ReplayAddress::new(raw_path())
        .with_speed(ReplaySpeed::Max)
        .port_id();
    let mut config = SessionConfig::new(id, SerialConfig::default());
    config.read_timeout = Duration::from_millis(10);
    let session = Session::open(&router, config).expect("the fixture opens");

    let frames = FrameStore::default();
    let reader = frames.reader();
    let ingest = Ingest::spawn_with(
        session.events(),
        serialist_core::Store::default(),
        Box::new(move || -> Vec<Box<dyn serialist_core::ChunkSink>> {
            vec![Box::new(CodecSink::from_factory(factory, frames, None))]
        }),
        Box::new(|| {}),
    );

    // The replay ends with the session's `Disconnected`, which closes the event channel
    // and ends the ingest thread with every chunk handled.
    let deadline = Instant::now() + Duration::from_secs(10);
    while !ingest.is_finished() {
        assert!(Instant::now() < deadline, "the replay did not finish");
        std::thread::sleep(Duration::from_millis(2));
    }
    let chunks = ingest.stats().chunks;
    let connection = ingest.connection();
    ingest.join().expect("the ingest thread ran cleanly");
    drop(session);

    assert_eq!(
        connection.description.as_deref(),
        Some("replay:race-session.bin (max)")
    );
    let error = match connection.state {
        serialist_core::LinkState::Disconnected { error } => error,
        other => panic!("expected the replay to end disconnected, got {other:?}"),
    };
    assert_eq!(
        error.as_deref(),
        Some(TransportError::Disconnected.to_string().as_str()),
        "the replay ends when the capture does"
    );
    let decoded = reader.snapshot();
    (
        decoded.frames().map(|(_, frame)| frame.clone()).collect(),
        chunks,
    )
}

fn lua_factory() -> Arc<dyn CodecFactory> {
    Arc::new(bundled_race_lua(LuaLimits::default()).expect("the bundled plugin loads"))
}

#[test]
fn replaying_the_fixture_decodes_like_the_file() {
    let capture = fixture();
    let t0 = Instant::now();
    let direct = timeless(
        &decode_chunks(&mut AirohaRace::new(), &[&capture.raw], t0),
        t0,
    );
    // Not an empty comparison: the device logged all along and printed its lines.
    let kinds = |kind: &str| direct.iter().filter(|f| f.kind == kind).count();
    assert!(kinds("log") >= 90, "{} log frames", kinds("log"));
    assert!(kinds("text") >= 20, "{} text frames", kinds("text"));
    assert_eq!(kinds("codec_error"), 0);

    let rx_chunks = capture.parse_timing().unwrap().rx().count() as u64;
    let (rust, rust_chunks) = replay_decoded(AirohaRace::factory());
    let (lua, lua_chunks) = replay_decoded(lua_factory());
    // At `max` every read returns one recorded chunk, so the session sees the chunks the
    // recording saw.
    assert_eq!(rust_chunks, rx_chunks);
    assert_eq!(lua_chunks, rx_chunks);

    let rust = timeless(&rust, t0);
    let lua = timeless(&lua, t0);
    assert_eq!(
        rust, direct,
        "the Rust codec on the replay, against the file"
    );
    assert_eq!(
        lua, rust,
        "the Lua codec on the replay, against the Rust codec"
    );
}

#[test]
fn replay_keeps_the_recorded_chunk_boundaries() {
    const NANO: Duration = Duration::from_nanos(1);
    let capture = fixture();
    let timing = capture.parse_timing().unwrap();
    let rx: Vec<_> = timing.rx().collect();
    let schedule = timing.schedule(capture.raw.len() as u64);
    // Without a real number of chunks the loop below proves little.
    assert!(rx.len() > 100, "{} chunks", rx.len());
    assert_eq!(schedule.len(), rx.len(), "the sidecar covers the raw file");

    let clock = Arc::new(ManualClock::new());
    let factory = ReplayTransportFactory::with_clock(clock.clone());
    let id = ReplayAddress::new(raw_path())
        .with_speed(ReplaySpeed::REALTIME)
        .port_id();
    let Transport {
        mut reader,
        description,
        ..
    } = factory.open(&id, &SerialConfig::default()).unwrap();
    assert_eq!(description, "replay:race-session.bin (1x)");

    let start = clock.now();
    let first = rx[0].0;
    let mut buf = vec![0u8; 64 * 1024];
    for (n, (chunk, (at, offset, len))) in schedule.iter().zip(&rx).enumerate() {
        // The schedule is the sidecar's times, counted from the first chunk.
        assert_eq!(chunk.at, *at - first, "chunk {n}");
        assert_eq!((chunk.offset, chunk.len), (*offset, *len), "chunk {n}");

        // Probe with a zero timeout (a non-blocking read on a manual clock): one
        // nanosecond early there is nothing, and exactly on time there is the chunk.
        let elapsed = clock.now() - start;
        if chunk.at > elapsed {
            clock.advance(chunk.at - elapsed - NANO);
            assert_eq!(
                reader.read(&mut buf, Duration::ZERO).unwrap(),
                0,
                "chunk {n} came early"
            );
            clock.advance(NANO);
        }
        assert_eq!(clock.now() - start, chunk.at, "chunk {n}");
        let got = reader.read(&mut buf, Duration::ZERO).unwrap();
        let (from, to) = (*offset as usize, (*offset + *len) as usize);
        assert_eq!(&buf[..got], &capture.raw[from..to], "chunk {n}");
    }
    assert!(matches!(
        reader.read(&mut buf, Duration::ZERO),
        Err(TransportError::Disconnected)
    ));
}

#[test]
fn the_replayed_session_decodes_to_the_pinned_frames() {
    let (frames, _) = replay_decoded(AirohaRace::factory());
    insta::with_settings!({
        snapshot_path => "fixtures/snapshots",
        prepend_module_to_snapshot => false,
        omit_expression => true,
    }, {
        insta::assert_snapshot!("race_session_frames", render(&frames));
    });
}
