//! The decoded frames of a fixed RACE capture, pinned with insta.
//!
//! The capture is `tests/fixtures/race-capture.bin`, generated by [`corpus::generate`]
//! with the seed below. The snapshot, `tests/fixtures/snapshots/`, is what both the Rust
//! and the Lua codec make of it. After an intended change to the generator, rewrite the
//! capture with `SERIALIST_BLESS_FIXTURES=1 cargo test -p serialist-plugins --test
//! snapshots`, then review the snapshot change (`cargo insta review`, or
//! `INSTA_UPDATE=always` and read the diff).

mod common;

use std::fmt::Write as _;
use std::path::PathBuf;
use std::time::Instant;

use serialist_core::{Frame, Value, codec::encode_hex};
use serialist_plugins::corpus;
use serialist_plugins::race::AirohaRace;

use common::{decode_chunks, lua_race, timeless};

const SEED: u64 = 0x5E71_A115_2026_0930;
const SEGMENTS: usize = 160;

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/race-capture.bin")
}

fn fixture() -> Vec<u8> {
    std::fs::read(fixture_path()).expect("the capture fixture is checked in")
}

#[test]
fn the_capture_is_the_generated_corpus() {
    let generated = corpus::generate(SEED, SEGMENTS);
    if std::env::var_os("SERIALIST_BLESS_FIXTURES").is_some() {
        std::fs::write(fixture_path(), &generated).expect("write the fixture");
    }
    assert!(
        fixture() == generated,
        "the capture no longer matches the generator; see this file's docs to rewrite it"
    );
}

fn value(value: &Value) -> String {
    match value {
        Value::Str(s) if s.len() > 72 => {
            let cut = s.floor_char_boundary(72);
            format!("{:?} ..+{}", &s[..cut], s.len() - cut)
        }
        Value::Str(s) => format!("{s:?}"),
        Value::Bytes(b) if b.len() > 24 => {
            format!("[{} ..+{}]", encode_hex(&b[..24], " "), b.len() - 24)
        }
        Value::Bytes(b) => format!("[{}]", encode_hex(b, " ")),
        other => other.to_string(),
    }
}

fn render(frames: &[Frame]) -> String {
    let mut out = String::new();
    for f in frames {
        let fields: Vec<String> = f
            .fields
            .iter()
            .map(|(name, v)| format!("{name}={}", value(v)))
            .collect();
        let _ = writeln!(
            out,
            "{:>6}..{:<6} {:<10} {:<7} {}",
            f.raw.start,
            f.raw.end,
            f.kind,
            f.severity,
            fields.join(" ")
        );
        if f.kind != "text" {
            let _ = writeln!(out, "{:>15} {}", "|", f.summary);
        }
    }
    out
}

#[test]
fn the_capture_decodes_to_the_pinned_frames() {
    let bytes = fixture();
    let t0 = Instant::now();
    let rust = decode_chunks(&mut AirohaRace::new(), &[&bytes], t0);
    let lua = decode_chunks(&mut lua_race(), &[&bytes], t0);
    assert_eq!(rust, lua, "the Rust and Lua codecs disagree on the capture");
    // Cut as a UART driver might (and as badly as possible), the frames are the same.
    for sizes in [vec![1], vec![7], vec![64, 3, 4096, 1]] {
        let chunks = corpus::split(&bytes, &sizes);
        let rust_cut = decode_chunks(&mut AirohaRace::new(), &chunks, t0);
        let lua_cut = decode_chunks(&mut lua_race(), &chunks, t0);
        assert_eq!(rust_cut, lua_cut, "chunks of {sizes:?}");
        assert_eq!(
            timeless(&rust_cut, t0),
            timeless(&rust, t0),
            "chunks of {sizes:?}"
        );
    }
    insta::with_settings!({
        snapshot_path => "fixtures/snapshots",
        prepend_module_to_snapshot => false,
        omit_expression => true,
    }, {
        insta::assert_snapshot!("race_capture_frames", render(&rust));
    });
}
